describe('App', () => {
  it('should display a page header', () => {
    cy.visit('http://localhost:3000/')
      .get('h1')
      .should('have.text', 'Turing Cafe Reservations')
  })

  it('should display current reservations', () => {
    cy.visit('http://localhost:3000/')
      .get('article')
      .get('h2')
      .should('exist')
      .get('.time')
      .should('exist')
      .get('.date')
      .should('exist')
      .get('.number')
      .should('exist')
      .get('.cancel-booking')
  })

  it('should have an input form', () => {
    cy.visit('http://localhost:3000/')
      .get('input[name="name"]')
      .get('input[name="date"]')
      .get('input[name="time"]')
      .get('input[name="number"]')
      .get('.submit-booking')
  })

  it('should be able to type into each input', () => {
    cy.visit('http://localhost:3000/')
      .get('input[name="name"]')
      .type('Phil')
      .should('have.value', 'Phil')
      .get('input[name="date"]')
      .type('05/07')
      .should('have.value', '05/07')
      .get('input[name="time"]')
      .type('6:00')
      .should('have.value', '6:00')
      .get('input[name="number"]')
      .type('2')
      .should('have.value', '2')
      .get('.submit-booking')
  })
  
  it('should be able to submit a booking and view it on the page', () => {
    cy.visit('http://localhost:3000/')
    .get('input[name="name"]')
    .type('Phil')
    .get('input[name="date"]')
    .type('05/07')
    .get('input[name="time"]')
    .type('6:00')
    .get('input[name="number"]')
    .type('2')
    .get('.submit-booking').click()
    .get('h2')
    .contains('Phil')
  })
})
